# configs/default.yaml
paths:
  raw_root: C:/Users/user/Documents/data_raw      # 원본 보관(다른 드라이브 추천)
  e_daic:
    audio_dir: ${paths.raw_root}/E-DAIC/Audio
    transcript_dir: ${paths.raw_root}/E-DAIC/Transcript
    features_dir: ${paths.raw_root}/E-DAIC/Features   # egemaps/mfcc/openface/vgg/densenet
  daic_woz:
    audio_dir: ${paths.raw_root}/DAIC-WOZ/Audio
    transcript_dir: ${paths.raw_root}/DAIC-WOZ/Transcript
    features_dir: ${paths.raw_root}/DAIC-WOZ/Features # CLNF, COVAREP
  dvlog:
    root: ${paths.raw_root}/D-VLOG
    acoustic: ${paths.raw_root}/D-VLOG/acoustic    # or dir
    visual:   ${paths.raw_root}/D-VLOG/visual     # or dir
    labels:   ${paths.raw_root}/D-VLOG/labels.csv

outputs:
  processed_root: ./data/processed               # 트림/마스킹 반영본
  cache_root: ./data/cache                       # 윈도 캐시(.npz)와 index.csv

modalities:
  use_audio: true
  use_landmarks: true
  use_privileged: true
  privileged:
    use_cnn_vgg16: true
    use_cnn_densenet201: true
    use_openface_pose_gaze_aus: true

preprocessing:
  strategy: cut_head_mask_rest                   # "앞부분 컷 + 나머지는 마스크/드롭"
  ellie_regex: "(?i)hi\\s*i[' ]?m\\s*ellie"
  vad:
    aggressiveness: 2                            # 0..3 (3이 가장 공격적) - 마스크용
    frame_ms: 30                                 # VAD 판단 프레임 길이
    speech_ratio_threshold: 0.5                  # window_cache 단계에서 마스크 사용
  denoise:
    enabled: true                                # 물리적 감산(선택)
  egemaps_25lld_reextract: true
  normalize_landmarks: "zface"
  dvlog_landmark_norm: "minmax"
  resample:
    audio_hz: 100  # eGeMAPS 25 LLD @ 10ms
    vis_hz: 33.33  #openface ~30fps
    cnn_hz: 1

features:
  egemaps:
    use_clean_reextract: true                    # 트림 후 eGeMAPS LLD 재추출
    target_hz: 100
  mfcc:
    use_as_privileged: true                      # 교사 특권(프레임마스크만)
  openface:
    use_as_privileged: true
  vgg16:
    use_as_privileged: true
  densenet201:
    use_as_privileged: true

windowing:
  length_s: 4.0
  hop_secs: 2.5
  pad: "repeat"
  min_valid_ratio : 0.6
  stride_s: 1.0
  base_rate_hz: 100   # 캐시 기준 시간해상도(오디오는 그대로, 다른 모달은 '윈도 내 모달별 시계열'로 저장)

labels:
  e_daic_labels_dir: ${paths.raw_root}/E-DAIC/labels
  daic_woz_labels_dir: ${paths.raw_root}/DAIC-WOZ/labels
  dvlog_labels_csv: ${paths.raw_root}/D-VLOG/labels.csv

merge_policy:
  prefer_daic_for_overlap: true    # 300–492 중복 세션 처리 규칙

eval:
  threshold: 0.5
  metrics: ["acc","f1","precision","recall","auc","mse","mae","pearson"]