paths:
  raw_root: C:/Users/user/Documents/data_raw   # 원본 보관(수정 금지)

  daic_woz:
    transcript_dir: ${paths.raw_root}/DAIC-WOZ/Transcript
    features_dir:   ${paths.raw_root}/DAIC-WOZ/Features   # CLNF, COVAREP
    labels_dir:     ${paths.raw_root}/DAIC-WOZ/labels

  e_daic:
    audio_dir:      ${paths.raw_root}/E-DAIC/Audio        # 모든 참가자 오디오(300~718 공용)
    transcript_dir: ${paths.raw_root}/E-DAIC/Transcript   # 493 이후 transcript
    features_dir:   ${paths.raw_root}/E-DAIC/Features     # MFCC/OpenFace/VGG16/DenseNet201
    labels_dir:     ${paths.raw_root}/E-DAIC/labels

  dvlog:
    root:     ${paths.raw_root}/D-VLOG
    acoustic: ${paths.raw_root}/D-VLOG/acoustic          # *.npy (25 LLD @100Hz)
    visual:   ${paths.raw_root}/D-VLOG/visual            # *.npy (68*2 dlib)
    labels:   ${paths.raw_root}/D-VLOG/labels.csv

outputs:
  processed_root: ./data/processed                       # 전처리/정렬 반영본
  cache_root:     ./data/cache                           # 윈도 캐시(.npz) + index.csv

# processed 내부의 재추출/클린 경로(미러 구조 고정)
processed:
  daic_woz:
    reegemaps25: ${outputs.processed_root}/DAIC-WOZ/ReEgemaps25LLD
    features:    ${outputs.processed_root}/DAIC-WOZ/Features   # CLNF/COVAREP cleaned
    transcript:  ${outputs.processed_root}/DAIC-WOZ/Transcript
  e_daic:
    reegemaps25: ${outputs.processed_root}/E-DAIC/ReEgemaps25LLD
    features:    ${outputs.processed_root}/E-DAIC/Features     # MFCC/OpenFace/CNN cleaned
    transcript:  ${outputs.processed_root}/E-DAIC/Transcript
    audio:       ${outputs.processed_root}/E-DAIC/Audio        # (선택) denoise 결과
  dvlog:
    acoustic:    ${outputs.processed_root}/D-VLOG/acoustic     # (선택) 정규화본
    visual:      ${outputs.processed_root}/D-VLOG/visual

modalities:
  use_audio: true
  use_landmarks: true
  use_privileged: true
  privileged:
    use_cnn_vgg16: true
    use_cnn_densenet201: true
    use_openface_pose_gaze_aus: true
    use_mfcc: true

preprocessing:
  strategy: cut_head_mask_rest                   # 앞부분 컷 + 나머지는 마스크/드롭
  ellie_regex: "(?i)hi\\s*i[' ]?m\\s*ellie"
  vad:
    aggressiveness: 2
    frame_ms: 30
    speech_ratio_threshold: 0.5
  denoise:
    enabled: true
  egemaps_25lld_reextract: true
  normalize_landmarks: "zface"       # DAIC/E-DAIC -> zface norm
  dvlog_landmark_norm: "minmax"      # D-VLOG -> min-max norm
  resample:
    audio_hz: 100   # eGeMAPS 25 LLD @ 10ms
    vis_hz: 33.33   # OpenFace ~30fps
    cnn_hz: 1

features:
  egemaps:
    use_clean_reextract: true
    target_hz: 100
  mfcc:
    use_as_privileged: true
  openface:
    use_as_privileged: true
  vgg16:
    use_as_privileged: true
  densenet201:
    use_as_privileged: true

windowing:
  length_s: 4.0
  stride_s: 1.0
  hop_secs: 2.5
  pad: "repeat"
  min_valid_ratio: 0.6
  base_rate_hz: 100

labels:
  daic_woz:
    train_split: ${paths.daic_woz.labels_dir}/train_split_Depression_AVEC2017.csv
    dev_split:   ${paths.daic_woz.labels_dir}/dev_split_Depression_AVEC2017.csv
    test_split:  ${paths.daic_woz.labels_dir}/full_test_split.csv

  e_daic:
    train_split: ${paths.e_daic.labels_dir}/train_split.csv
    dev_split:   ${paths.e_daic.labels_dir}/dev_split.csv
    test_split:  ${paths.e_daic.labels_dir}/test_split.csv
    detailed:    ${paths.e_daic.labels_dir}/Detailed_PHQ8_Labels.csv

  dvlog:
    labels_csv:  ${paths.dvlog.labels}

merge_policy:
  prefer_daic_for_overlap: true    # 300–492 overlap 해결

eval:
  threshold: 0.5
  metrics: ["acc","f1_macro","f1_weighted","precision","recall","auc","mse","mae","pearson","spearman"]
