teacher:
  audio_dim: 25
  vis_dim: 136
  vgg_dim: 4096
  densenet_dim: 1920
  aus_dim: 35                  # 예시(실제 OpenFace csv 기준으로 맞춰야 함)
  hidden: 128
  lstm_layers: 2
  attn_heads: 4
  dropout: 0.2
  fusion: "cross_attn+transformer"

student:
  audio_dim: 25
  vis_dim: 136                 # audio-only면 무시
  hidden: 128
  lstm_layers: 2
  attn_heads: 4
  dropout: 0.2
  use_landmarks: false         # 배포버전: false
